apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie-frontend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gyeongnamit/movie_recommend_frontend
    path: k8s
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true